### ISSUE TITLE
Unsupported operand types at `dokan-lite/includes/Commission.php:267`

### ISSUE THREAD

**Issue by hasdfa** [getdokan/dokan#2486]
### Bug Description

```
Error Details
=============
An error of type E_ERROR was caused in line 267 of the file /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Commission.php. Error message: Uncaught TypeError: Unsupported operand types: string - float in /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Commission.php:267
Stack trace:
#0 /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Order/Admin/Hooks.php(167): WeDevs\Dokan\Commission->get_earning_by_order(Object(Automattic\WooCommerce\Admin\Overrides\Order), 'admin')
#1 /WEBSITE_ROOT/public_html/wp-includes/class-wp-hook.php(324): WeDevs\Dokan\Order\Admin\Hooks->shop_order_custom_columns('admin_commissio...', 104534)
#2 /WEBSITE_ROOT/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /WEBSITE_ROOT/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /WEBSITE_ROOT/public_html/wp-admin/includes/class-wp-posts-list-table.php(1403): do_action('manage_shop_ord...', 'admin_commissio...', 104534)
#5 /WEBSITE_ROOT/public_html/wp-admin/includes/class-wp-list-table.php(1802): WP_Posts_List_Table->column_default(Object(WP_Post), 'admin_commissio...')
#6 /WEBSITE_ROOT/public_html/wp-admin/includes/class-wp-posts-list-table.php(1437): WP_List_Table->single_row_columns(Object(WP_Post))
#7 /WEBSITE_ROOT/public_html/wp-admin/includes/class-wp-posts-list-table.php(839): WP_Posts_List_Table->single_row(Object(WP_Post), 0)
#8 /WEBSITE_ROOT/public_html/wp-admin/includes/class-wp-posts-list-table.php(815): WP_Posts_List_Table->_display_rows(Array, 0)
#9 /WEBSITE_ROOT/public_html/wp-admin/includes/class-wp-list-table.php(1712): WP_Posts_List_Table->display_rows()
#10 /WEBSITE_ROOT/public_html/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder()
#11 /WEBSITE_ROOT/public_html/wp-admin/edit.php(503): WP_List_Table->display()
#12 {main}
thrown
```

### Step To Reproduce

I'm not sure, but seems like it appears after open `draft` orders tab

### Expected Behaviour

No uncaught exceptions

### Actual Behaviour

Uncaught TypeError: Unsupported operand types: `string - float`

### Environment (please complete the following information)

```shell
1. Dokan Version: v3.14.3
2. Dokan Pro Version: v3.14.1
3. WooCommerce Version: v9.5.1
4. Browser: Chrome (Chromium Engine Version 131.0.6778.140)
5. Current Theme: Storefront
6. WordPress version 6.7.1
7. PHP version 8.2.26
```

**Comment by Aunshon** [comment]
Hello @hasdfa ,
I hope this message finds you well. While we were unable to reproduce the issue you reported during our debugging session, we've submitted a pull request that we believe addresses the problem.
Could you please review the pull request and verify if it resolves your issue? If you're still experiencing problems, we'd appreciate if you could contact our support team and provide your staging site credentials. This would allow us to investigate further and ensure the solution works for your specific case.
Thank you for your cooperation.

Pull Request:
* https://github.com/getdokan/dokan/pull/2489

**Comment by oliviertassinari** [comment]
Fix would be

```diff
diff --git a/includes/Commission/Settings/OrderItem.php b/includes/Commission/Settings/OrderItem.php
index e3ee631c..c239927f 100644
--- a/includes/Commission/Settings/OrderItem.php
+++ b/includes/Commission/Settings/OrderItem.php
@@ -64,9 +64,9 @@ class OrderItem implements InterfaceSetting {
if ( $order_id && OrderUtil::is_hpos_enabled() ) {
             $order = dokan()->order->get( $order_id );
-            $item_total = $order->get_meta( '_dokan_item_total' );
+            $item_total = (float) $order->get_meta( '_dokan_item_total' );
         } else {
-            $item_total = get_post_meta( $order_id, '_dokan_item_total', true );
+            $item_total = (float) get_post_meta( $order_id, '_dokan_item_total', true );
         }
$product_price = (float) wc_format_decimal( $this->product_price_to_calculate_commission );
```
